CREATE DATABASE glance;
GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost'  IDENTIFIED BY "kFUVAMyZgUgcD8lSG9aA8kH2HPmo7fP0";
GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%'  IDENTIFIED BY "kFUVAMyZgUgcD8lSG9aA8kH2HPmo7fP0";
