CREATE DATABASE neutron;
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY "CiH7J2U88DhWNECBYQH7A5Okyu3F4uRe";
GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY "CiH7J2U88DhWNECBYQH7A5Okyu3F4uRe";
